# Welcome to Adriano J. Holanda pages!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adriano J. Holanda pages
description: > # this means to ignore newlines until "baseurl:"
  These pages contain only enough information to communicate
  professional data, some ideas and concepts, and projects' content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aholanda.github.io" # the base hostname & protocol for your site

github_username: aholanda

# Build settings
markdown: kramdown
